### ISSUE TITLE
Able to enter Tardis ignoring doors (locked and unlocked)

### ISSUE THREAD

**Issue by undertalenerd** [CommandrMoose/TardisRefined#431] opened 2024-12-28 06:24 UTC
### Issue description

No matter the lock/unlock or open/closed door states, a player can walk into the Tardis from the outside as if the doors don't exist. I have roughly 160 mods, but I'm fairly confident none of them are the cause, as on the pre-Christmas update this worked fine.

### Steps to reproduce

1. Walk into Tardis from outside ignoring any door state
2. You are now in the Tardis

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

0.16.9

### Tardis Refined version

v2.1.1

### Other relevant versions

![image](https://github.com/user-attachments/assets/e62cc0e8-244a-425a-ab45-778f18f0d312)
![image](https://github.com/user-attachments/assets/174af52c-2243-49a0-9113-9caa36280b57)

**Comment by Jeryn99** [comment] 2024-12-28 11:00
Duplicate of https://github.com/WhoCraft/TardisRefined/issues/422

**Closed as completed by Jeryn99** 2024-12-28 11:00 UTC
