### ISSUE TITLE
Bit of a weird one. Local Server refuses connection, then crashes.

### ISSUE THREAD

**Issue by Dumpling00** [CommandrMoose/TardisRefined#327] opened 2024-06-29 02:46 UTC
### Issue description

So I am not 100% sure this is even caused by tardis refined, but that's what I see being mentioned in the crash report so I have nowhere else to turn to.

I have this local server, been playing with a couple friends for a little over a month - I haven't played in the last few days to work but I left the server open to let them play for a few hours a day. Nothing has changed in terms of updates and everything was working allegedly up until yesterday. Now I tried to log in and suddenly, it hangs on "encryptying", then times me out. Server holds, so I try to connect again, but that's when the server, upon trying to log me in again, kicks me out and crashes.

Here's the report. Any help would be highly appreciated. I don't know if this was maybe caused by one of my friends doing something weird with any item from the Tardis Refined mod (We don't have a tardis yet), so there's that.

https://gist.github.com/Dumpling00/d1728ddc05d28c66f76ab517ba74704b

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.15.10

### Tardis Refined version

v2.0.3

**Comment by Jeryn99** [comment] 2024-06-30 11:23
Duplicate of https://github.com/WhoCraft/TardisRefined/issues/326

**Closed as completed by Jeryn99** 2024-06-30 11:23 UTC
Labels: work-in-progress, 1.20.1, 1.20.2
