### ISSUE TITLE
Tardis will change locations without taking off, just by setting coordinates.

### ISSUE THREAD

**Issue by The-Rose-Composer** [CommandrMoose/TardisRefined#427] opened 2024-12-27 06:39 UTC
### Issue description

I saw that a very similar issue was reported, but I am not sure if this is a separate issue or the exact same one.
This is very similar to the bug report called "Instantaneous travel" but I think they may have missed some stuff. If this ties into the same issue and it has already been resolved, please skip this bug report and resolve it before reading.

What I saw happen is that when you set the coordinates that you want the Tardis to travel to, it changes both the Destination value and the GPS value. The GPS is where the Tardis thinks it is, and the Destination is where the Tardis is set to go. Setting the coordinates should only cause the Destination to change, but it also changes the GPS to change. 

This leads to an odd issue, for when you exit the Tardis after changing the coordinates, you will get out at the exact coordinates you put in, no matter where they are. Weirdly though, the Tardis exterior will not be there. 

The other post that said that the Tardis would move instantaneously was very similar, however perhaps the reason why the Tardis was able to get there instantaneously is because although the exterior is not at the location you selected, the Tardis thinks that it actually is at the coordinates you selected, so it when you take off it would be as though you were landing at the very spot you dematted from. I again do not know if this is the same issue or not, but I thought I would go ahead and submit it none the less. Also, the new vortex update is actually so sick I had no clue this was going to be dropping so soon!

This seems to happen in both singleplayer and on servers from what I have tested

### Steps to reproduce

1.Fly the Tardis a few times to a few different locations (the issue only occurs after a couple flights)
2. Set the coordinates for where you want to go and do _not_ take off
3. Walk outside of the Tardis, and you will be at the coordinates you selected, yet there will be no exterior block there.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.0

### Tardis Refined version

v2.1.1

**Comment by Jeryn99** [comment] 2024-12-27 11:53
Hey, I have a few questions:

Mod list? We know that this problem is present with Immersive Portals for some reason
Does this happen after a flight, during a flight or before even taking off?

**Comment by The-Rose-Composer** [comment] 2024-12-27 14:56
1. Immersive Portals I don't have installed which makes this all more confusing. I know Embeddium and Oculus change things about rendering and game data, so maybe that's what is happening?

Here is my complete mod list:
Embeddium
JourneyMap
Just Enough Items (JEI)
Oculus
Tardis Refined

2. This happens before a flight, for example, while the Tardis is landed. Altering the coordinates will change the real time GPS on the monitor, and then walking outside of the door will put me at those coordinates without having to take off.

**Comment by Jeryn99** [comment] 2024-12-27 15:40
I'll look into this more, if I end up with more questions can you provide answers?

Also, are you able to provide me with the world you're using along with a mrpack/cursepack of the mods you're using?
I know I can just download them myself, but I don't know the exact versions and all

**Comment by The-Rose-Composer** [comment] 2024-12-27 16:45
Yes of course! I am also on Discord as @fastcargo
Here is the modlist and the world. When you join the world, you should be standing inside of the glitched Tardis which appears to be having the issue. Changing any of the coordinates will result in it changing where you exit the Tardis without even taking off. I think the only way to get back inside of the Tardis is to teleport to interior because the exterior disappeared for some reason.

[trmodpack.zip](https://github.com/user-attachments/files/18262134/trmodpack.zip)

https://drive.google.com/file/d/1JrdP8Fa4UCeNty1itFhY39w7EMRLvqbY/view?usp=sharing

If these links don't work ask me and I will try again

**Comment by Jeryn99** [comment] 2024-12-27 19:24
![img](https://media.tenor.com/fCmMoTM8G_IAAAAM/im-going-crazy-hey-arnold.gif)

I think I found the cause...


![image](https://github.com/user-attachments/assets/542420c9-fc89-414d-a310-fe8b05d4e90e)

versus

![image](https://github.com/user-attachments/assets/1dd05b08-7907-43ed-acbe-85802cd450ed)

**Comment by Jeryn99** [comment] 2024-12-28 00:32
Fixed with the assistance of @fastcargo99

**Closed as completed by Jeryn99** 2024-12-28 00:32 UTC
Labels: bug, work-in-progress, forge, fabric, 1.20.1
