### ISSUE TITLE
Root shell doesnt let you out.

### ISSUE THREAD

**Issue by sheet315** [CommandrMoose/TardisRefined#139] opened 2023-05-06 15:39 UTC
### Issue description

When using Immersive Portals, you cannot exit the tardis to start terraforming. And after exiting the tardis and you try to get in again, you cant and when u place another tardis and get in, you cant get out at all.

### Steps to reproduce

1. Install Tardis Refined v1 & Immersive Portals
2. Grow/place a root shell.
3. Go inside
4. Place the terraformer multiblock
5. Go outside
6. Nothing happens
7. Try going inside (doesn't work)
8. Place another one
9. Go inside
10. You are now locked inside and cannot get out

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

43.2.0

### Tardis Refined version

v1.0

### Other relevant versions

Immersive portals version: 2.3.5-mc1.19.2-forge

**Comment by Suff99** [comment] 2023-05-06 22:17
Duplicate of https://github.com/CommandrMoose/TardisRefined/issues/138

**Closed by Suff99** 2023-05-06 22:17 UTC
