### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cn1t** [CommandrMoose/TardisRefined#297] opened 2024-06-02 09:31 UTC
### Issue description

I only have Tardis Refined and Immersive Portals in the curseforge modpack

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'tardis_refined'!

### Steps to reproduce

1. Curseforge modpack with Tardis refined, immersive portals
2. Start game

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.15.11

### Tardis Refined version

v2.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/j6G8UrKG

**Comment by 50ap5ud5** [comment] 2024-06-02 09:38
Duplicate of #278. This is an issue that will be resolved next release. For now, do not use Immersive Portals and Tardis Refined togethor.

**Closed as completed by 50ap5ud5** 2024-06-02 09:38 UTC
