### ISSUE TITLE
Valkyrien Skies

### ISSUE THREAD

**Issue by protogencpu** [CommandrMoose/TardisRefined#352] opened 2024-08-12 04:33 UTC
### Issue description

The game crashes when shearing the root

### Steps to reproduce

1. Let the root grow
2. Shear root
3. Game crashes

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.2.17

### Tardis Refined version

v2.0.4

### Other relevant versions

Valkyrien Skies - V.2.3.0-beta.5 Forge

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/gTL3zazm

**Comment by TARDISSYT** [comment] 2024-08-20 22:44
Now, I'm no Minecraft mod dev, but I'm pretty sure since Valkyrien Skies uses blocks outside of the world border (by millions) it is causing issues with TARDIS Refined. Honestly I think your best bet would be to remove Valkyrien Skies or TARDIS Refined. Just my opinion.

**Comment by Jeryn99** [comment] 2024-08-21 16:51
Duplicate of: https://github.com/WhoCraft/TardisRefined/issues/324

**Closed as completed by Jeryn99** 2024-08-21 16:51 UTC
