### ISSUE TITLE
TARDIS interior door collision makes the player unable to get in/out IF immersive portals is active

### ISSUE THREAD

**Issue by Zyfies** [CommandrMoose/TardisRefined#193] opened 2024-01-05 09:09 UTC
### Issue description

interior door collision makes it ***almost*** impossible to get through ***if*** immersive portals is present (can go through if ender pearl is thrown at the bottom of the door)

_portal will work if interior portal is moved at least -0.125 (but the portal will look a bit ugly because it would be bulging out of the door frame, and if the door is closed and reopened the portal will be reset back to its original position)_

this issue seems to be previously fixed (on version 1.0) but was broken again (on version 1.0.1)

### Steps to reproduce

1. have Immersive Portals and TARDIS Refined in the same profile
2. get a terraformed TARDIS in-game
3. try to get in or out

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric - 0.15.3

### Tardis Refined version

v1.0

### Other relevant versions

TARDIS Refined version 1.0.1
Immersive Portals version 2.3.2

**Comment by Jeryn99** [comment] 2024-01-05 09:12
Duplicate of https://github.com/Suff99/TardisRefined/issues/174

Please ensure to check before creating a issue

**Closed as completed** 2024-01-05 09:13 UTC
