### ISSUE TITLE
tardis not working after crashing it 1.20.1 version 2.0.7

### ISSUE THREAD

**Issue by electroreal1** [CommandrMoose/TardisRefined#381] opened 2024-10-16 22:14 UTC
### Issue description

i crashed the tardis and it wont get fixed even after being right clicked with an ice block on it

### Steps to reproduce

i tried to use the tardis and then a part broke and now its not repairing

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

forge 47.3.0

### Tardis Refined version

v2.0.7

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://mclo.gs/fGDxQsJ

**Comment by Jeryn99** [comment] 2024-10-19 09:34
Duplicate of https://github.com/WhoCraft/TardisRefined/issues/351
Please check if your issue exists before posting

**Closed as completed by Jeryn99** 2024-10-19 09:34 UTC
